### ISSUE TITLE
Localize `Try Again` button 

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1170]
de Erneut versuchen
es-ES Volver a intentarlo 
fr Réessayer
id Coba Lagi
pl Spróbuj ponownie 
pt-BR Tentar novamente 
ru Попробовать снова
zh-TW 重試

- [x] Add automatic localization
- [x] Localize existing Snippets

**Comment by jkt230** [comment]
Giorgos we see "Try again" in our current S2D snippets but because it's not localized, that means that all S2D snippets live (like our F100 snippets in other locales) are using the English "Try again" which isn't a good user experience. Let me know if you can get this change in sooner than later. Thank you!

**Comment by glogiotatidis** [comment]
Jean the change on the Firefox side is still in nightly and will be available with Firefox 71. So our release and beta channel users don't see the new button. 

Will fix in the next days anyways but wanted to clarify that this hasn't hit release yet.

**Comment by glogiotatidis** [comment]
Found also `zh-cn`, `cs`, `it`, `pt-pt` in https://transvision.mozfr.org/string/?entity=browser/browser/newtab/newtab.ftl:newtab-discovery-empty-section-topstories-try-again-button&repo=gecko_strings

Will discuss about `es-ar`, `es-cl` and `es-mx` tomorrow with OMN team

**Comment by glogiotatidis** [comment]
Complete! :fireworks:
