### ISSUE TITLE
Enable more permissions/roles so non-admin users can build snippets but not publish

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#353]
To streamline the IPC process, we want to enable content writers to build snippets within the service for review

**Comment by glogiotatidis** [comment]
note for when we start building: This requires more detailed permissions which are described in the IPC 2018 requirements document.

**Comment by glogiotatidis** [comment]
From Snippets Service [Product Requirements doc](https://docs.google.com/a/mozilla.com/document/d/12bCVSEQnnTkvrLHzMh3yGY7taUE7KFYZpiZ7WL2F_q0/edit?disco=AAAABi1f-l0)

"""
Giorgos:
Currently we have 2 level permissions:

1. Users can add/edit/delete/publish Desktop Snippets
2. Users can add/edit/delete/publish
Android Snippets

We can add more so that

1. Users can add/edit/delete all desktop
2. Users can publish all desktop
3. Users can add/edit/delete only snippets they have created
4. Users can publish only theirs
5. User can publish only on nightly

etc

Can you please make a list of the must have and nice to have permissions?
Show less


Jean Collings
8:39 PM Jan 12
I imagine that for each channel (release, beta, nightly, dev edition) there would be:
1) Viewer (who can only view)
2) Creator (who can view and draft - add/edit/delete)
3) Publisher/Admin (who can view, draft and publish)


Giorgos Logiotatidis
9:29 AM Jan 15
1) Viewer views all snippets (disabled or otherwise) or just active snippets?

Jean Collings
8:25 PM Jan 17
1) view all snippets please
"""

**Comment by glogiotatidis** [comment]
I removed my assignment b/c probably i won't get to this before may 7th. @pmac feel free to take it on if you have capacity

**Comment by glogiotatidis** [comment]
Interesting projects:
 - https://github.com/silentsokolov/django-admin-permissions
 - https://github.com/lukaszb/django-guardian
 - https://github.com/dfunckt/django-rules

**Comment by glogiotatidis** [comment]
Created: 
 - #534 
 - #535

**Comment by glogiotatidis** [comment]
Closing this one in favor of the newly created ones.
