### ISSUE TITLE
Develop a plan for special links and actions in new Activity Stream

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#521]
Snippets service uses a number of special links to trigger actions in the browser, namely:
 * Linking to `about:accounts` triggers `gSnippetsMap.showFirefoxAccounts()`
 * Linking to `uitour:showMenu:appMenu` and `uitour:hideMenu:appMenu`, shows and hides the appMenu accordingly, using UITour.

It's very possible that in the future we'd like to use additional UITour -or other- special functionality.

We'd like to maintain and extend as required those special links, which in turn would be converted to the proper actions from the AS addon.

**Comment by glogiotatidis** [comment]
@k88hudson do you think that's something we can get on FF62?

**Comment by glogiotatidis** [comment]
@k88hudson can you please provide a list of available actions?

**Comment by k88hudson** [comment]
(see also https://docs.google.com/document/d/1E_1hxrU4GNMwKz6rwN4Iw8LoTefUmUl6wneyJ9-7U84/edit#)

Available actions include:
 - `OPEN_PRIVATE_BROWSER_WINDOW`: This opens a blank private browsing tab in a new window
- `OPEN_ABOUT_PAGE`: This is necessary to open pages that are not otherwise linkable due to security reasons, such as about:preferences
-`SHOW_FIREFOX_ACCOUNTS`: opens the firefox accounts signup page (about:accounts?action=signup&entrypoint=snippets)

If additional actions are needed, let us know and we can file a ticket to support them

**Comment by glogiotatidis** [comment]
AS Router work required to make this happen is tracked in bug [1478569](https://bugzilla.mozilla.org/show_bug.cgi?id=1478569) and we have issues #652 and #653 to track the implementation of the individual actions. Marking this one complete.
