### ISSUE TITLE
iCal / Google Calendar feed does not work as expected

### ISSUE THREAD

**Issue by ldwright** [mozmeao/snippets-service#649]
We'd love to be able to use the snippets service to easily see & share editorial visibility in a Calendar format (rather than just a list format like https://snippets-admin.moz.works/ currently provides) as to what snippets are currently published and/or scheduled to be published in the upcoming weeks/months (across everything and drilled down per channel/by locale, etc.).

Workaround until this gets built could be to fix the current Google Calendar integration issue, so we can utilize that instead in the meantime.

**Comment by glogiotatidis** [comment]
> the current Google Calendar integration issue

@ldwright would you mind filing an issue about the current Google Calendar integration issue b/c I'm not aware of the issue?

**Comment by glogiotatidis** [comment]
> @ldwright would you mind filing an issue about the current Google Calendar integration issue b/c I'm not aware of the issue?

friendly ping @ldwright

**Comment by ldwright** [comment]
@mediaChick may be able to describe the issue with the Google integration better than I can - I was not around when it was being used, so I'm unsure what changed/went wrong. I just know that we're currently managing editorial planning via Google Sheets in a very manual fashion now.

However, as discussed earlier today, I feel like that workaround can be taken off the table and we should try to focus efforts on creating a solution/interface in the admin tool itself, if possible.

Also, can you please confirm why this link (https://snippets-admin.moz.works/) no longer shows the list of snippets that are published? It was the link that we used to share out with people when they asked what was running, but now we're having to point them to our Google Sheets instead. Thanks!

**Comment by glogiotatidis** [comment]
The link won't list new Snippet because the code supporting this required a full revamp. I decided not to do this and drop the functionality because I had provided you with the iCal / Google calendar integration.

I understand that this is not used anymore (You say "when it was being used") but this is the first time I hear this. 

Please do explain why the integration doesn't work so we can work together a solution. 

Also for better collaboration: When something is requested and delivered but doesn't work as expected because reasons, let's try to keep the feedback loop open and make it work, otherwise we both lose.

**Comment by glogiotatidis** [comment]
Since this issue is becoming more about the gCal integration and not the calendar view I'll rename this and track the Calendar creation in another issue

**Comment by mediaChick** [comment]
@glogiotatidis The gCal is called "Firefox in-product messaging calendar" and I don't know what is causing the calendar to not display all the published snippets. 

I do know that Jean created the cal, and when I saw that it wasn't working (after Jean left for mat leave) I asked @bensternthal to take a look. From what I recall, he couldn't identify what the issue was.

That's all I know.

**Comment by glogiotatidis** [comment]
OK. The last email on this was from a year ago (20 Oct '17) were Jean verified it working and asked questions about having a separate calendar by targeting parameter. I replied that "I suggest that we file bugs even with more generic asks and have the discussions there (so context and decisions don't get lost in email threads)." 

Anyhow, point is that today the calendar *is* working and lists all 648 published snippets as of today.

The URL of the calendar is `https://snippets-admin.mozilla.org/feeds/snippets-enabled.ics` and can you integrate it to gCal or whichever calendaring application you prefer.

If the current way it works doesn't cover your requirements and can be improved, I'll re-iterate my position to file issues and ask what you need.

I'm going to close this one out now. Thanks.

**Comment by mediaChick** [comment]
Thanks for the link! It works really well, but now that we have hundreds of F100 snippet running without start/end dates the calendar is gigantic. 

Since the calendar is for people outside of the snippet admin to see what's running in P100, can you modify the calendar feed so that it's only snippets that have a start/end date?

**Comment by glogiotatidis** [comment]
File issues with what you need. We can have only the snippets with start and end or different links with different locales or other filtering. Decide on what's useful and describe it in an issue.  Thanks
