### ISSUE TITLE
Set Cachalot to use shared cache in production

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#768]
Currently Cachalot caching framework is set to use locmem. Set it to use redis in prod

**Comment by jgmize** [comment]
As I recall, we switched the snippets cache from redis to locmem due to repeated issues with the redis instance failing under load. This also impacted basket, which was sharing the redis instance, and we decided to try locmem before spending the extra money on a dedicated cache for snippets.

Also, while using locmem for cache does have a negative impact on the cache hit ratio, by eliminating network latency it can actually improve overall performance in some cases. It certainly did for bedrock.

**Comment by glogiotatidis** [comment]
Valuable info @jgmize, definitely something to keep in mind. Lots of architectural / performance changes since then, so maybe it's worth taking another look eventually but not a top priority.

**Comment by glogiotatidis** [comment]
Deprecated by #1094
