### ISSUE TITLE
ASR Snippets: Admin will not save snippets with short/tracking links

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#806]
It wouldn't save snippets with the short/tracking link we've been using for IRL (in this case: http://smarturl.it/irl_s03e07?IQid=snippet/)

**Comment by glogiotatidis** [comment]
The problem is not the short link but the insecure `http` link. This is a design / security decision, that all links must be secure. You can use the same link with `https`. 

The error from the admin site:

![image](https://user-images.githubusercontent.com/584352/47550820-0d8bd100-d909-11e8-9c52-94b631813306.png)

I filed issue #808 to improve the error message.
