### ISSUE TITLE
Snippet Fx Accounts Attribution Debugging

### ISSUE THREAD

**Issue by metadave** [mozmeao/snippets-service#912]
let's track work on snippets attribution debugging in this issue.

@zerokarmaleft @bensternthal @glogiotatidis @jpetto

**Comment by zerokarmaleft** [comment]
@glogiotiatidis The top-sheet summary is some F100 snippets over 2018 were found to have pointed to URLs like `https://www.mozilla.org/firefox/accounts/?utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=es_f100_week11_fxasync&utm_term=9181&utm_content=rel`. As the user clicks through any of the possible CTAs to start the registration process, the UTM parameters are possibly being stripped or overwritten.  Start-of-registration funnel metrics look suspiciously low, but I'd appreciate being able to rule out this possibility.

**Comment by glogiotatidis** [comment]
OK filing in some blanks to limit the problem space:
 - "over 2018" that means we 're investigating the old pre-ASR system as the transition to ASR happened in 2019. 
 - The above said, do we want to spend time to investigate what happened on the old system? Do we want to confirm what happens in the new system? Both?
 - I verified with a pre-ASR copy of Firefox that the snippets preserve the UTM parameters. I.e. when a user clicks on a snippet with a link like `https://www.mozilla.org/firefox/accounts/?utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=es_f100_week11_fxasync&utm_term=9181&utm_content=rel` their browser visits the complete link.
- @zerokarmaleft you say "as the user click through any .. to start the registration process":
  - The Snippet links to mozilla.org, so there's no registration happening here.
  - The linked mozilla.org page seems to be using it's own UTM parameters, overriding the snippet ones when you click the `Create firefox account` link. Maybe that's the issue here?

@zerokarmaleft let me know how you want to move this investigation fwd.

**Comment by jkt230** [comment]
Jumping in here for clarity based on what Giorgos is saying, for both 2018 and 2019 using snippets to point to`https://www.mozilla.org/firefox/accounts/?utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=es_f100_week11_fxasync&utm_term=9181&utm_content=rel` means that users will go to the landing page but as soon as they click to sign up for an account, the snippet UTM parameters are being overriden. Therefore, at this point snippets will not be attributed to any Firefox Account sign ups.

**Comment by zerokarmaleft** [comment]
@jkt230 So is this a landing page coding issue to capture and pass on the referring UTM parameters from a snippet click-through?

**Comment by jkt230** [comment]
Correct. The solutions are:
1) Create a landing page separately for snippets only or
2) Figure out if that current landing page is flexible enough to pass through the referring UTM parameters from a snippet click-through

**Comment by zerokarmaleft** [comment]
@jkt230 For comparison, what were the landing pages for snippets that *were* correctly attributed in 2018?

**Comment by jkt230** [comment]
Pointing to this: https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v3&entrypoint=snippets&utm_source=snippet&utm_content=66&utm_campaign=&utm_term=&

**Comment by zerokarmaleft** [comment]
Thanks @jkt230. @glogiotatidis, The idea here is that we'd like to use the landing page that explains FxA before presenting the signup form -- i.e. clicking from a snippet and landing directly at a registration form is a poor user experience and probably has low conversion.

**Comment by jpetto** [comment]
The links/form on https://www.mozilla.org/en-US/firefox/accounts/ already include `utm_` params. Here is one example from that page:

https://accounts.firefox.com/signup?service=sync&context=fx_desktop_v3&entrypoint=accounts-page&utm_source=accounts-page&utm_content=accounts-page-top-cta&utm_medium=referral&utm_campaign=fxa-benefits-page

I don't think it would be too difficult to write some JS to change some/all `utm_` values in the above link based on the querystring of the current URL.

I think the question is, which `utm_` values should be changed, and how will that change impact other metrics? We're likely seeing inflated metrics from mozilla.org (as the hits are effectively being handed off from snippets to mozilla.org).

**Comment by glogiotatidis** [comment]
> Thanks @jkt230. @glogiotatidis, The idea here is that we'd like to use the landing page that explains FxA before presenting the signup form -- i.e. clicking from a snippet and landing directly at a registration form is a poor user experience and probably has low conversion.

Understood. As @jpetto suggests we're are able to update the mozilla.org page to set the `utm_` params based on the querystring of the current URL. The mozilla.org team should advise which is the best way to do this.

Next steps:
 - File an issue under `mozilla/bedrock` to discuss the best ways to count snippets attribution

This is technically *not* a `snippets-service` issue. I'll keep this issue open as a placeholder until there 're other issues filed and actions taken to fix this under the relevant projects.

**Comment by glogiotatidis** [comment]
This is now tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1527318

Thanks all!
